services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - PRICE_FEED_URL=${PRICE_FEED_URL:-https://interview.switcheo.com/prices.json}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
